version: "v2.26.1"
services:
  web:
    image: "nginx:latest"
    container_name: "nginx-web"
    ports:
      - "8090:80"
    volumes:
      - "./src:/usr/share/nginx/html"
      - "./nginx/conf.d:/etc/nginx/conf.d"
    links:
      - "php8.2-fpm"
    depends_on:
      - "php8.2-fpm"
  mysql:
    image: "mysql:latest"
    container_name: "mysql-web"
    environment:
      - "MYSQL_ROOT_PASSWORD=123456"
      - "MYSQL_DATABASE=anydb"
    expose:
      - "3306"
    ports:
      - "3306:3306"
    restart: always
    command: ["--default-authentication-plugin=mysql_native_password"]
    volumes:
      - "./mysql/data:/var/lib/mysql"
  php8.2-fpm:
    image: "php:latest"
    container_name: 'php8.2-fpm'
    links:
      - "mysql"
    volumes:
      - "./src:/var/www/html"
    depends_on:
      - "mysql"